---
apiVersion: v1
kind: Namespace
metadata:
  name: oudns
  labels:
    app.kubernetes.io/part-of: maserutel-enterprise-systems-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: oudsmns
  labels:
    app.kubernetes.io/part-of: maserutel-enterprise-systems-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-validation
  labels:
    app.kubernetes.io/part-of: maserutel-enterprise-systems-lab
